"""phase5_communication_governance_analytics_tables

Revision ID: 6bc680ff3919
Revises: f38e2faa450a
Create Date: 2026-09-01 03:34:57.708811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc680ff3919'
down_revision: Union[str, None] = 'f38e2faa450a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('TASK', 'REQUIREMENT', 'MEETING', 'DIRECTIVE', 'ANNOUNCEMENT', 'TRANSFER', 'FORM', 'REPORT', 'SYSTEM', name='notification_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_resource_type', sa.String(length=50), nullable=True),
    sa.Column('related_resource_id', sa.Uuid(), nullable=True),
    sa.Column('read_status', sa.Enum('UNREAD', 'READ', 'DISMISSED', name='notification_read_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notifications_recipient_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index('ix_notifications_recipient_read', 'notifications', ['recipient_id', 'read_status'], unique=False)
    op.create_table('ownership_transfers',
    sa.Column('resource_type', sa.Enum('EVENT', 'TASK', 'REQUIREMENT', name='transfer_resource_type_enum'), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('current_owner_id', sa.UUID(), nullable=False),
    sa.Column('requested_owner_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'COMPLETED', name='transfer_status_enum'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['current_owner_id'], ['users.id'], name=op.f('fk_ownership_transfers_current_owner_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_ownership_transfers_requested_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_owner_id'], ['users.id'], name=op.f('fk_ownership_transfers_requested_owner_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_ownership_transfers_reviewed_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ownership_transfers'))
    )
    op.create_index(op.f('ix_ownership_transfers_id'), 'ownership_transfers', ['id'], unique=False)
    op.create_index('ix_transfers_current_owner', 'ownership_transfers', ['current_owner_id'], unique=False)
    op.create_index('ix_transfers_requested_owner', 'ownership_transfers', ['requested_owner_id'], unique=False)
    op.create_index('ix_transfers_resource', 'ownership_transfers', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_transfers_status', 'ownership_transfers', ['status'], unique=False)
    op.create_table('system_configs',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.Enum('STRING', 'INTEGER', 'FLOAT', 'BOOLEAN', 'JSON', name='config_value_type_enum'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_system_configs_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_configs'))
    )
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=False)
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    op.create_index('ix_system_configs_key_active', 'system_configs', ['key', 'is_active'], unique=False)
    op.create_table('announcements',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='announcement_priority_enum'), nullable=False),
    sa.Column('scope', sa.Enum('ALL', 'VERTICAL', 'USER', name='announcement_scope_enum'), nullable=False),
    sa.Column('vertical_id', sa.UUID(), nullable=True),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'EXPIRED', 'ARCHIVED', name='announcement_status_enum'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_announcements_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('fk_announcements_target_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], name=op.f('fk_announcements_vertical_id_verticals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.create_index('ix_announcements_published_at', 'announcements', ['published_at'], unique=False)
    op.create_index('ix_announcements_status', 'announcements', ['status'], unique=False)
    op.create_index('ix_announcements_vertical_id', 'announcements', ['vertical_id'], unique=False)
    op.create_table('communication_logs',
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('communication_type', sa.Enum('EMAIL', 'MEETING', 'OFFICIAL_MESSAGE', 'NOTICE', 'CALL', 'OTHER', name='communication_type_enum'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('sender_info', sa.String(length=255), nullable=False),
    sa.Column('recipient_info', sa.String(length=255), nullable=False),
    sa.Column('vertical_id', sa.UUID(), nullable=True),
    sa.Column('related_resource_type', sa.String(length=50), nullable=True),
    sa.Column('related_resource_id', sa.Uuid(), nullable=True),
    sa.Column('reference_link', sa.String(length=1024), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RECORDED', 'ARCHIVED', name='communication_log_status_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_communication_logs_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], name=op.f('fk_communication_logs_vertical_id_verticals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communication_logs'))
    )
    op.create_index('ix_comm_logs_date_time', 'communication_logs', ['date_time'], unique=False)
    op.create_index('ix_comm_logs_vertical_id', 'communication_logs', ['vertical_id'], unique=False)
    op.create_index(op.f('ix_communication_logs_id'), 'communication_logs', ['id'], unique=False)
    op.create_table('directives',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('issued_by_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.Enum('ALL', 'VERTICAL', 'USER', name='directive_scope_enum'), nullable=False),
    sa.Column('vertical_id', sa.UUID(), nullable=True),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='directive_priority_enum'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'ARCHIVED', name='directive_status_enum'), nullable=False),
    sa.Column('requires_acknowledgement', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], name=op.f('fk_directives_issued_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('fk_directives_target_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], name=op.f('fk_directives_vertical_id_verticals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_directives'))
    )
    op.create_index('ix_directives_effective_date', 'directives', ['effective_date'], unique=False)
    op.create_index(op.f('ix_directives_id'), 'directives', ['id'], unique=False)
    op.create_index('ix_directives_status', 'directives', ['status'], unique=False)
    op.create_index('ix_directives_vertical_id', 'directives', ['vertical_id'], unique=False)
    op.create_table('directive_acknowledgements',
    sa.Column('directive_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACKNOWLEDGED', name='acknowledgement_status_enum'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['directive_id'], ['directives.id'], name=op.f('fk_directive_acknowledgements_directive_id_directives'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_directive_acknowledgements_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_directive_acknowledgements')),
    sa.UniqueConstraint('directive_id', 'user_id', name='uq_directive_user_acknowledgement')
    )
    op.create_index('ix_directive_ack_user_id', 'directive_acknowledgements', ['user_id'], unique=False)
    op.create_index(op.f('ix_directive_acknowledgements_id'), 'directive_acknowledgements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_directive_acknowledgements_id'), table_name='directive_acknowledgements')
    op.drop_index('ix_directive_ack_user_id', table_name='directive_acknowledgements')
    op.drop_table('directive_acknowledgements')
    op.drop_index('ix_directives_vertical_id', table_name='directives')
    op.drop_index('ix_directives_status', table_name='directives')
    op.drop_index(op.f('ix_directives_id'), table_name='directives')
    op.drop_index('ix_directives_effective_date', table_name='directives')
    op.drop_table('directives')
    op.drop_index(op.f('ix_communication_logs_id'), table_name='communication_logs')
    op.drop_index('ix_comm_logs_vertical_id', table_name='communication_logs')
    op.drop_index('ix_comm_logs_date_time', table_name='communication_logs')
    op.drop_table('communication_logs')
    op.drop_index('ix_announcements_vertical_id', table_name='announcements')
    op.drop_index('ix_announcements_status', table_name='announcements')
    op.drop_index('ix_announcements_published_at', table_name='announcements')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index('ix_system_configs_key_active', table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_id'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index('ix_transfers_status', table_name='ownership_transfers')
    op.drop_index('ix_transfers_resource', table_name='ownership_transfers')
    op.drop_index('ix_transfers_requested_owner', table_name='ownership_transfers')
    op.drop_index('ix_transfers_current_owner', table_name='ownership_transfers')
    op.drop_index(op.f('ix_ownership_transfers_id'), table_name='ownership_transfers')
    op.drop_table('ownership_transfers')
    op.drop_index('ix_notifications_recipient_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')

    # Drop PostgreSQL native enums
    sa.Enum(name='acknowledgement_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='directive_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='directive_priority_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='directive_scope_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='communication_log_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='communication_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='announcement_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='announcement_scope_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='announcement_priority_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='config_value_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='transfer_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='transfer_resource_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='notification_read_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='notification_type_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
