"""phase3_core_operational_tables

Revision ID: 7783f3e05eec
Revises: 6beb22ccc447
Create Date: 2026-09-01 03:11:22.433705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7783f3e05eec'
down_revision: Union[str, None] = '6beb22ccc447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_entries',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('category', sa.Enum('ACTIVITY', 'MILESTONE', 'REVIEW_MEETING', 'INTERVIEW', 'REPORT_DEADLINE', 'ONBOARDING', 'ORIENTATION', 'EVENT', 'MEETING', name='activity_category_enum'), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='calendar_priority_enum'), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='calendar_status_enum'), nullable=False),
    sa.Column('deadline_type', sa.Enum('HARD_DEADLINE', 'SOFT_DEADLINE', 'INFORMATIONAL', name='deadline_type_enum'), nullable=False),
    sa.Column('audience', sa.Enum('ALL', 'ORGANIZATION', 'VERTICAL', 'SPECIFIC_USERS', name='calendar_audience_enum'), nullable=False),
    sa.Column('vertical_id', sa.UUID(), nullable=True),
    sa.Column('event_reference', sa.String(length=255), nullable=True),
    sa.Column('resource_link', sa.String(length=1000), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_calendar_entries_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], name=op.f('fk_calendar_entries_vertical_id_verticals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_entries'))
    )
    op.create_index(op.f('ix_calendar_entries_activity_date'), 'calendar_entries', ['activity_date'], unique=False)
    op.create_index(op.f('ix_calendar_entries_audience'), 'calendar_entries', ['audience'], unique=False)
    op.create_index(op.f('ix_calendar_entries_category'), 'calendar_entries', ['category'], unique=False)
    op.create_index(op.f('ix_calendar_entries_created_by_id'), 'calendar_entries', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_calendar_entries_deadline_type'), 'calendar_entries', ['deadline_type'], unique=False)
    op.create_index(op.f('ix_calendar_entries_id'), 'calendar_entries', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_entries_priority'), 'calendar_entries', ['priority'], unique=False)
    op.create_index(op.f('ix_calendar_entries_status'), 'calendar_entries', ['status'], unique=False)
    op.create_index(op.f('ix_calendar_entries_title'), 'calendar_entries', ['title'], unique=False)
    op.create_index(op.f('ix_calendar_entries_vertical_id'), 'calendar_entries', ['vertical_id'], unique=False)
    op.create_table('daily_work_reports',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vertical_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('work_summary', sa.Text(), nullable=False),
    sa.Column('tasks_completed', sa.Text(), nullable=True),
    sa.Column('blockers', sa.Text(), nullable=True),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('next_actions', sa.Text(), nullable=True),
    sa.Column('evidence_links', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'REVIEWED', 'RETURNED', 'FLAGGED', name='daily_report_status_enum'), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('review_comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_daily_work_reports_reviewer_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_work_reports_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], name=op.f('fk_daily_work_reports_vertical_id_verticals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_work_reports')),
    sa.UniqueConstraint('user_id', 'report_date', name='uq_daily_work_reports_user_date')
    )
    op.create_index(op.f('ix_daily_work_reports_id'), 'daily_work_reports', ['id'], unique=False)
    op.create_index(op.f('ix_daily_work_reports_report_date'), 'daily_work_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_daily_work_reports_reviewer_id'), 'daily_work_reports', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_daily_work_reports_status'), 'daily_work_reports', ['status'], unique=False)
    op.create_index(op.f('ix_daily_work_reports_user_id'), 'daily_work_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_daily_work_reports_vertical_id'), 'daily_work_reports', ['vertical_id'], unique=False)
    op.create_table('issues',
    sa.Column('date_raised', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vertical_id', sa.UUID(), nullable=False),
    sa.Column('event_reference', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('raised_by_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('sensitivity', sa.Enum('NORMAL', 'SENSITIVE', 'CONFIDENTIAL', name='issue_sensitivity_enum'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'BLOCKED', 'ESCALATED', 'RESOLVED', 'CLOSED', 'CANCELLED', name='issue_status_enum'), nullable=False),
    sa.Column('action_required', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalation_target', sa.String(length=255), nullable=True),
    sa.Column('escalation_action', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_link', sa.String(length=1000), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_issues_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], name=op.f('fk_issues_raised_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], name=op.f('fk_issues_vertical_id_verticals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issues'))
    )
    op.create_index(op.f('ix_issues_assigned_to_id'), 'issues', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_issues_date_raised'), 'issues', ['date_raised'], unique=False)
    op.create_index(op.f('ix_issues_id'), 'issues', ['id'], unique=False)
    op.create_index(op.f('ix_issues_raised_by_id'), 'issues', ['raised_by_id'], unique=False)
    op.create_index(op.f('ix_issues_sensitivity'), 'issues', ['sensitivity'], unique=False)
    op.create_index(op.f('ix_issues_status'), 'issues', ['status'], unique=False)
    op.create_index(op.f('ix_issues_title'), 'issues', ['title'], unique=False)
    op.create_index(op.f('ix_issues_vertical_id'), 'issues', ['vertical_id'], unique=False)
    op.create_table('tasks',
    sa.Column('vertical_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('assigned_by_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Enum('ROUTINE', 'EVENT', 'MILESTONE', 'DOCUMENTATION', 'MEETING_FOLLOW_UP', name='task_type_enum'), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='task_priority_enum'), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED', 'CANCELLED', name='task_status_enum'), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('health', sa.Enum('ON_TRACK', 'AT_RISK', 'OVERDUE', 'BLOCKED', 'COMPLETE', name='task_health_enum'), nullable=False),
    sa.Column('date_assigned', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blockers', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('latest_update', sa.Text(), nullable=True),
    sa.Column('evidence_link', sa.String(length=1000), nullable=True),
    sa.Column('deficiency', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('completion_percentage >= 0 AND completion_percentage <= 100', name=op.f('ck_tasks_`chk_tasks_completion_percentage`')),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_tasks_assigned_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_tasks_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], name=op.f('fk_tasks_vertical_id_verticals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_assigned_by_id'), 'tasks', ['assigned_by_id'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_to_id'), 'tasks', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_tasks_deadline'), 'tasks', ['deadline'], unique=False)
    op.create_index(op.f('ix_tasks_health'), 'tasks', ['health'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.create_index(op.f('ix_tasks_vertical_id'), 'tasks', ['vertical_id'], unique=False)
    op.create_table('weekly_reports',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vertical_id', sa.UUID(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('completed_work', sa.Text(), nullable=True),
    sa.Column('outstanding_work', sa.Text(), nullable=True),
    sa.Column('blockers', sa.Text(), nullable=True),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('priorities_next_week', sa.Text(), nullable=True),
    sa.Column('supervisor_comments', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'REVIEWED', name='weekly_report_status_enum'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_weekly_reports_reviewer_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_weekly_reports_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], name=op.f('fk_weekly_reports_vertical_id_verticals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_reports')),
    sa.UniqueConstraint('user_id', 'week_start_date', name='uq_weekly_reports_user_week_start')
    )
    op.create_index(op.f('ix_weekly_reports_id'), 'weekly_reports', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_reports_reviewer_id'), 'weekly_reports', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_weekly_reports_status'), 'weekly_reports', ['status'], unique=False)
    op.create_index(op.f('ix_weekly_reports_user_id'), 'weekly_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_weekly_reports_vertical_id'), 'weekly_reports', ['vertical_id'], unique=False)
    op.create_index(op.f('ix_weekly_reports_week_end_date'), 'weekly_reports', ['week_end_date'], unique=False)
    op.create_index(op.f('ix_weekly_reports_week_start_date'), 'weekly_reports', ['week_start_date'], unique=False)
    op.create_table('issue_history',
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_issue_history_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_issue_history_issue_id_issues'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_history'))
    )
    op.create_index(op.f('ix_issue_history_actor_id'), 'issue_history', ['actor_id'], unique=False)
    op.create_index(op.f('ix_issue_history_id'), 'issue_history', ['id'], unique=False)
    op.create_index(op.f('ix_issue_history_issue_id'), 'issue_history', ['issue_id'], unique=False)
    op.create_index(op.f('ix_issue_history_timestamp'), 'issue_history', ['timestamp'], unique=False)
    op.create_table('task_comments',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_task_comments_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_comments_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_comments'))
    )
    op.create_index(op.f('ix_task_comments_author_id'), 'task_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_task_comments_id'), 'task_comments', ['id'], unique=False)
    op.create_index(op.f('ix_task_comments_task_id'), 'task_comments', ['task_id'], unique=False)
    op.create_table('task_history',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('previous_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_task_history_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_history_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_history'))
    )
    op.create_index(op.f('ix_task_history_actor_id'), 'task_history', ['actor_id'], unique=False)
    op.create_index(op.f('ix_task_history_id'), 'task_history', ['id'], unique=False)
    op.create_index(op.f('ix_task_history_task_id'), 'task_history', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_history_timestamp'), 'task_history', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_history_timestamp'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_task_id'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_id'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_actor_id'), table_name='task_history')
    op.drop_table('task_history')
    op.drop_index(op.f('ix_task_comments_task_id'), table_name='task_comments')
    op.drop_index(op.f('ix_task_comments_id'), table_name='task_comments')
    op.drop_index(op.f('ix_task_comments_author_id'), table_name='task_comments')
    op.drop_table('task_comments')
    op.drop_index(op.f('ix_issue_history_timestamp'), table_name='issue_history')
    op.drop_index(op.f('ix_issue_history_issue_id'), table_name='issue_history')
    op.drop_index(op.f('ix_issue_history_id'), table_name='issue_history')
    op.drop_index(op.f('ix_issue_history_actor_id'), table_name='issue_history')
    op.drop_table('issue_history')
    op.drop_index(op.f('ix_weekly_reports_week_start_date'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_week_end_date'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_vertical_id'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_user_id'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_status'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_reviewer_id'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_id'), table_name='weekly_reports')
    op.drop_table('weekly_reports')
    op.drop_index(op.f('ix_tasks_vertical_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_health'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deadline'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_by_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_issues_vertical_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_title'), table_name='issues')
    op.drop_index(op.f('ix_issues_status'), table_name='issues')
    op.drop_index(op.f('ix_issues_sensitivity'), table_name='issues')
    op.drop_index(op.f('ix_issues_raised_by_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_date_raised'), table_name='issues')
    op.drop_index(op.f('ix_issues_assigned_to_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_daily_work_reports_vertical_id'), table_name='daily_work_reports')
    op.drop_index(op.f('ix_daily_work_reports_user_id'), table_name='daily_work_reports')
    op.drop_index(op.f('ix_daily_work_reports_status'), table_name='daily_work_reports')
    op.drop_index(op.f('ix_daily_work_reports_reviewer_id'), table_name='daily_work_reports')
    op.drop_index(op.f('ix_daily_work_reports_report_date'), table_name='daily_work_reports')
    op.drop_index(op.f('ix_daily_work_reports_id'), table_name='daily_work_reports')
    op.drop_table('daily_work_reports')
    op.drop_index(op.f('ix_calendar_entries_vertical_id'), table_name='calendar_entries')
    op.drop_index(op.f('ix_calendar_entries_title'), table_name='calendar_entries')
    op.drop_index(op.f('ix_calendar_entries_status'), table_name='calendar_entries')
    op.drop_index(op.f('ix_calendar_entries_priority'), table_name='calendar_entries')
    op.drop_index(op.f('ix_calendar_entries_id'), table_name='calendar_entries')
    op.drop_index(op.f('ix_calendar_entries_deadline_type'), table_name='calendar_entries')
    op.drop_index(op.f('ix_calendar_entries_created_by_id'), table_name='calendar_entries')
    op.drop_index(op.f('ix_calendar_entries_category'), table_name='calendar_entries')
    op.drop_index(op.f('ix_calendar_entries_audience'), table_name='calendar_entries')
    op.drop_index(op.f('ix_calendar_entries_activity_date'), table_name='calendar_entries')
    op.drop_table('calendar_entries')

    # Drop PostgreSQL enum types
    sa.Enum(name='activity_category_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='calendar_priority_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='calendar_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='deadline_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='calendar_audience_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='daily_report_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='weekly_report_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='issue_sensitivity_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='issue_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='task_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='task_priority_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='task_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='task_health_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
