"""phase4_event_coordination_tables

Revision ID: f38e2faa450a
Revises: 7783f3e05eec
Create Date: 2026-09-01 03:24:31.454335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f38e2faa450a'
down_revision: Union[str, None] = '7783f3e05eec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('vertical_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Enum('TOURNAMENT', 'MATCH', 'WORKSHOP', 'CEREMONY', 'TRAINING', 'MEETING', 'OTHER', name='event_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PLANNING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'ARCHIVED', name='event_status_enum'), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('society_name', sa.String(length=255), nullable=True),
    sa.Column('event_head_id', sa.UUID(), nullable=True),
    sa.Column('primary_poc_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('resource_links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_events_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_head_id'], ['users.id'], name=op.f('fk_events_event_head_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_poc_id'], ['users.id'], name=op.f('fk_events_primary_poc_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], name=op.f('fk_events_vertical_id_verticals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_created_by_id'), 'events', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_events_event_head_id'), 'events', ['event_head_id'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=False)
    op.create_index(op.f('ix_events_planned_date'), 'events', ['planned_date'], unique=False)
    op.create_index(op.f('ix_events_primary_poc_id'), 'events', ['primary_poc_id'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_index(op.f('ix_events_vertical_id'), 'events', ['vertical_id'], unique=False)
    op.create_table('forms',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='form_status_enum'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('vertical_id', sa.UUID(), nullable=True),
    sa.Column('target_audience', sa.Enum('ALL', 'ORGANIZATION', 'VERTICAL', 'SPECIFIC_ROLES', name='form_audience_enum'), nullable=False),
    sa.Column('current_version_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_forms_owner_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], name=op.f('fk_forms_vertical_id_verticals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forms'))
    )
    op.create_index(op.f('ix_forms_id'), 'forms', ['id'], unique=False)
    op.create_index(op.f('ix_forms_name'), 'forms', ['name'], unique=False)
    op.create_index(op.f('ix_forms_owner_id'), 'forms', ['owner_id'], unique=False)
    op.create_index(op.f('ix_forms_status'), 'forms', ['status'], unique=False)
    op.create_index(op.f('ix_forms_vertical_id'), 'forms', ['vertical_id'], unique=False)
    op.create_table('requirements',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requesting_vertical_id', sa.UUID(), nullable=False),
    sa.Column('target_vertical_id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='requirement_priority_enum'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED', 'REJECTED', 'CANCELLED', name='requirement_status_enum'), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_requirements_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_requirements_requester_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requesting_vertical_id'], ['verticals.id'], name=op.f('fk_requirements_requesting_vertical_id_verticals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_vertical_id'], ['verticals.id'], name=op.f('fk_requirements_target_vertical_id_verticals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirements'))
    )
    op.create_index(op.f('ix_requirements_assignee_id'), 'requirements', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_requirements_deadline'), 'requirements', ['deadline'], unique=False)
    op.create_index(op.f('ix_requirements_id'), 'requirements', ['id'], unique=False)
    op.create_index(op.f('ix_requirements_priority'), 'requirements', ['priority'], unique=False)
    op.create_index(op.f('ix_requirements_requester_id'), 'requirements', ['requester_id'], unique=False)
    op.create_index(op.f('ix_requirements_requesting_vertical_id'), 'requirements', ['requesting_vertical_id'], unique=False)
    op.create_index(op.f('ix_requirements_status'), 'requirements', ['status'], unique=False)
    op.create_index(op.f('ix_requirements_target_vertical_id'), 'requirements', ['target_vertical_id'], unique=False)
    op.create_index(op.f('ix_requirements_title'), 'requirements', ['title'], unique=False)
    op.create_table('event_members',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_in_event', sa.Enum('HEAD', 'POC', 'COORDINATOR', 'VOLUNTEER', 'MEMBER', name='event_member_role_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'REMOVED', name='event_member_status_enum'), nullable=False),
    sa.Column('assigned_by_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_event_members_assigned_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_members_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_event_members_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_members')),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_member_event_user')
    )
    op.create_index(op.f('ix_event_members_event_id'), 'event_members', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_members_id'), 'event_members', ['id'], unique=False)
    op.create_index(op.f('ix_event_members_user_id'), 'event_members', ['user_id'], unique=False)
    op.create_table('event_readiness_items',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('PLANNING', 'COORDINATION', 'DOCUMENTATION', 'COMMUNICATIONS', 'TECHNICAL_PREPARATION', 'MOCK_TRIAL', 'FINAL_APPROVAL', 'EXECUTION_READINESS', name='readiness_category_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', 'NOT_APPLICABLE', name='readiness_status_enum'), nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_id', sa.UUID(), nullable=True),
    sa.Column('evidence_link', sa.String(length=1024), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('fk_event_readiness_items_assigned_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], name=op.f('fk_event_readiness_items_completed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_readiness_items_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_readiness_items'))
    )
    op.create_index(op.f('ix_event_readiness_items_category'), 'event_readiness_items', ['category'], unique=False)
    op.create_index(op.f('ix_event_readiness_items_event_id'), 'event_readiness_items', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_readiness_items_id'), 'event_readiness_items', ['id'], unique=False)
    op.create_index(op.f('ix_event_readiness_items_status'), 'event_readiness_items', ['status'], unique=False)
    op.create_table('form_versions',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transformation_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], name=op.f('fk_form_versions_form_id_forms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], name=op.f('fk_form_versions_published_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_versions')),
    sa.UniqueConstraint('form_id', 'version_number', name='uq_form_version_form_number')
    )
    op.create_index(op.f('ix_form_versions_form_id'), 'form_versions', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_versions_id'), 'form_versions', ['id'], unique=False)
    op.create_table('meetings',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('vertical_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('meeting_type', sa.Enum('INTERNAL_SYNC', 'VERTICAL_REVIEW', 'CORE_COORDINATION', 'EMERGENCY', 'ORIENTING', 'OTHER', name='meeting_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='meeting_status_enum'), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('meeting_url', sa.String(length=1024), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_meetings_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], name=op.f('fk_meetings_organizer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], name=op.f('fk_meetings_vertical_id_verticals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meetings'))
    )
    op.create_index(op.f('ix_meetings_event_id'), 'meetings', ['event_id'], unique=False)
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_index(op.f('ix_meetings_meeting_date'), 'meetings', ['meeting_date'], unique=False)
    op.create_index(op.f('ix_meetings_meeting_type'), 'meetings', ['meeting_type'], unique=False)
    op.create_index(op.f('ix_meetings_organizer_id'), 'meetings', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_index(op.f('ix_meetings_title'), 'meetings', ['title'], unique=False)
    op.create_index(op.f('ix_meetings_vertical_id'), 'meetings', ['vertical_id'], unique=False)
    op.create_table('requirement_messages',
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_requirement_messages_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_requirement_messages_requirement_id_requirements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_messages'))
    )
    op.create_index(op.f('ix_requirement_messages_id'), 'requirement_messages', ['id'], unique=False)
    op.create_index(op.f('ix_requirement_messages_requirement_id'), 'requirement_messages', ['requirement_id'], unique=False)
    op.create_table('form_submissions',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('form_version_id', sa.UUID(), nullable=False),
    sa.Column('submitter_id', sa.UUID(), nullable=False),
    sa.Column('submission_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'RETURNED', name='form_submission_status_enum'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('review_comments', sa.Text(), nullable=True),
    sa.Column('transformed_entity_type', sa.String(length=64), nullable=True),
    sa.Column('transformed_entity_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], name=op.f('fk_form_submissions_form_id_forms'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['form_version_id'], ['form_versions.id'], name=op.f('fk_form_submissions_form_version_id_form_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_form_submissions_reviewer_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], name=op.f('fk_form_submissions_submitter_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_submissions'))
    )
    op.create_index(op.f('ix_form_submissions_form_id'), 'form_submissions', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_submissions_form_version_id'), 'form_submissions', ['form_version_id'], unique=False)
    op.create_index(op.f('ix_form_submissions_id'), 'form_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_form_submissions_reviewer_id'), 'form_submissions', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_form_submissions_status'), 'form_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_form_submissions_submitter_id'), 'form_submissions', ['submitter_id'], unique=False)
    op.create_table('meeting_participants',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rsvp_status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'TENTATIVE', name='rsvp_status_enum'), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_participants_meeting_id_meetings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meeting_participants_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_participants')),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uq_meeting_participant_meeting_user')
    )
    op.create_index(op.f('ix_meeting_participants_id'), 'meeting_participants', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_participants_meeting_id'), 'meeting_participants', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_participants_user_id'), 'meeting_participants', ['user_id'], unique=False)
    op.add_column('tasks', sa.Column('event_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('meeting_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('requirement_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tasks_event_id'), 'tasks', ['event_id'], unique=False)
    op.create_index(op.f('ix_tasks_meeting_id'), 'tasks', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_tasks_requirement_id'), 'tasks', ['requirement_id'], unique=False)
    op.create_foreign_key(op.f('fk_tasks_meeting_id_meetings'), 'tasks', 'meetings', ['meeting_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_tasks_requirement_id_requirements'), 'tasks', 'requirements', ['requirement_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_tasks_event_id_events'), 'tasks', 'events', ['event_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tasks_event_id_events'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('fk_tasks_requirement_id_requirements'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('fk_tasks_meeting_id_meetings'), 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_requirement_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_meeting_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_event_id'), table_name='tasks')
    op.drop_column('tasks', 'requirement_id')
    op.drop_column('tasks', 'meeting_id')
    op.drop_column('tasks', 'event_id')
    op.drop_index(op.f('ix_meeting_participants_user_id'), table_name='meeting_participants')
    op.drop_index(op.f('ix_meeting_participants_meeting_id'), table_name='meeting_participants')
    op.drop_index(op.f('ix_meeting_participants_id'), table_name='meeting_participants')
    op.drop_table('meeting_participants')
    op.drop_index(op.f('ix_form_submissions_submitter_id'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_status'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_reviewer_id'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_id'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_form_version_id'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_form_id'), table_name='form_submissions')
    op.drop_table('form_submissions')
    op.drop_index(op.f('ix_requirement_messages_requirement_id'), table_name='requirement_messages')
    op.drop_index(op.f('ix_requirement_messages_id'), table_name='requirement_messages')
    op.drop_table('requirement_messages')
    op.drop_index(op.f('ix_meetings_vertical_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_title'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_organizer_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_meeting_type'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_meeting_date'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_event_id'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_form_versions_id'), table_name='form_versions')
    op.drop_index(op.f('ix_form_versions_form_id'), table_name='form_versions')
    op.drop_table('form_versions')
    op.drop_index(op.f('ix_event_readiness_items_status'), table_name='event_readiness_items')
    op.drop_index(op.f('ix_event_readiness_items_id'), table_name='event_readiness_items')
    op.drop_index(op.f('ix_event_readiness_items_event_id'), table_name='event_readiness_items')
    op.drop_index(op.f('ix_event_readiness_items_category'), table_name='event_readiness_items')
    op.drop_table('event_readiness_items')
    op.drop_index(op.f('ix_event_members_user_id'), table_name='event_members')
    op.drop_index(op.f('ix_event_members_id'), table_name='event_members')
    op.drop_index(op.f('ix_event_members_event_id'), table_name='event_members')
    op.drop_table('event_members')
    op.drop_index(op.f('ix_requirements_title'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_target_vertical_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_status'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_requesting_vertical_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_requester_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_priority'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_deadline'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_assignee_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_forms_vertical_id'), table_name='forms')
    op.drop_index(op.f('ix_forms_status'), table_name='forms')
    op.drop_index(op.f('ix_forms_owner_id'), table_name='forms')
    op.drop_index(op.f('ix_forms_name'), table_name='forms')
    op.drop_index(op.f('ix_forms_id'), table_name='forms')
    op.drop_table('forms')
    op.drop_index(op.f('ix_events_vertical_id'), table_name='events')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_primary_poc_id'), table_name='events')
    op.drop_index(op.f('ix_events_planned_date'), table_name='events')
    op.drop_index(op.f('ix_events_name'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_event_head_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_by_id'), table_name='events')
    op.drop_table('events')

    # Drop native enums
    sa.Enum(name='form_submission_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='form_audience_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='form_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='rsvp_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='meeting_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='meeting_type_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='requirement_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='requirement_priority_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='readiness_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='readiness_category_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='event_member_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='event_member_role_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='event_status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='event_type_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
